apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:b6sOHJKCu33Zj0VcMRZiMA==,iv:o9EWSmaXZDt/ASEzrtJfwOdGASj+LTi19foIiSbfFnE=,tag:g+32E8moJt86b1RzceaoXg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:uR+ZL5ENXBfJXXlJq6PPVhtF7YLvmeLpP0hGv9NZec7vkX0R,iv:qQ2a9WKe2RYhqk0VNYvqOvs+XBuXjUFLSi5nOyIUJtk=,tag:/6kxQDXotqx5enihkJwfSg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:fzWjGZGzMoZxmK35RQ==,iv:6Fvk0DyNRVoIuYSmqOVGd2f/5JJC1vU6rmrLtmZEUsc=,tag:EmVyXvax5wgoFXFn0s2hJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zjkf95ej2aadxllmk6xl4uexdnsvn648wdh6yhx3zuuqpcvn4szsnwchdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQy9GajlKU0plNmRSMkJZ
            Um5PWkp1NDdVN0F0QlQ4Wi9NVDJrMG5WYW5NCnlDblo5U0gxR1o2MmZlNFhpTnVD
            UmZLQVZ5WW5yMVJRMEJQYUJYazEvUEUKLS0tIEt5cVZpU3dSRkZkbWk1R2ZUYW5u
            QkVQWUFIME5PVkQ1QUJSeGFrQ0hGcVUKa9kMdzVpgAEF4wKSfSWgPzMA//s3grO7
            cyok2JQCokERjVaFoC4w9GV8ODllgKTzlk4B/OtIl0jUmJdX1axX5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T14:09:19Z"
    mac: ENC[AES256_GCM,data:XtyJIwv7jGciosw9pVknYX2sJ4U8hl+1JRjnCdm7V91QBQZN22i7lPe34UT4WwVo58cu+yZcdbHTDdNTg3DEAgXxCh3NWC97T6k4FwqIrQJ2rxiNE7OoJ+jx99GNNHUSLn2MZohopj0GmXX92Nx5vcZBFviXHZQn6p2upWlEGiA=,iv:vN9zOY2wiD5ZHM3z2+CLU+h8nkGR+Dw1rzFG3etPvvM=,tag:XkFDlQvVSvglHCGBUvsW0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
